### ISSUE TITLE
Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38

### ISSUE THREAD

**Issue by blueskyps2003** [nebulaai/ai-worker#5] opened 2019-04-24 16:00 UTC
when using AI worker, if you get such error message, you may need to upgrade your docker.
The following command maybe works:

sudo apt update && sudo apt upgrade

**Comment by flyworker** [comment] 2019-08-16 21:29
closed as cannot reproduce

**Closed as completed** 2019-08-16 21:28 UTC
